Naomi awareness of HIV status indicators (v2.1.2)
mrc-ide/hintr pull request #222
Opened 2020-12-05 16:49 UTC by jeffeaton

This linked to mrc-ide/naomi#184.

It pins to pins to branch naomi@aware-of-status and updates the hintr tests for new model options in Naomi and additional output indicators.

2020-12-05 20:43 UTC, r-ash requested changes

2020-12-05 20:43 UTC, r-ash commented on tests/testthat/test-api.R
> -test_that("don't change language if not asked to", {
:face_with_head_bandage:

2020-12-05 20:43 UTC, r-ash commented on typescript
> +Script started on Wed Dec  2 20:35:01 2020
Not sure where this is from?

2020-12-05 20:54 UTC, jeffeaton commented on typescript
> +Script started on Wed Dec  2 20:35:01 2020
🤷

2020-12-05 22:28 UTC, jeffeaton commented
936b88a adds new options to the validate options JSON payload, which should fix those erroring API tests.

I noticed a comment about model_options_valdate() 'endpoint not currently called'. I think that is out of date now?

https://github.com/mrc-ide/hintr/blob/39883b573abeecf3e3816fb7ca6c7e923b6ec839/R/endpoints.R#L107-L112

2020-12-07 14:48 UTC, r-ash approved these changes

2020-12-07 14:48 UTC, merged